title               : "Belal Ehmed"
description         : "Belal Ehmed's portfolio, Indie game programmer"
url                 : "https://ehmedbelal.github.io"
logo                : /assets/images/AI-Icon.jpg

author:
  name              : Belal Ehmed
  avatar            : "/assets/images/bio-photo.jpeg"
  email             : belalehmed.propanol@gmail.com
  twitter           : ehmed_belal
  facebook          : belal.ehmed.7
  github            : EhmedBelal
  linkedin          : anasiqbal55
  stackoverflow     : "1849539/anas-iqbal"
  steam             : anasiqbal

twitter:
  username          : Belal Ehmed
facebook:
  username          :
  app_id            :
  publisher         :
og_image            : # Open Graph/Twitter default site image

social:
  type              : Person
  name              : Belal Ehmed
  links:
    - "https://www.facebook.com/belal.ehmed.7"
    - "http://www.twitter.com/ehmed_belal"
    - "https://www.linkedin.com/in/anasiqbal55"
    - "https://github.com/EhmedBelal"
    - "http://stackoverflow.com/users/1849539/anas-iqbal"

comments:
  #discus: anasiqbal

webmaster_verifications:
  google: # n73NqY4YkDgmZyZzCJk6U_61k7hN0qcPe3jM64OY90M
  bing: #3ADDE9727FADDBB6F9B91DCC2ABF80C6

markdown: kramdown
highlighter: rouge
theme: minima
lsi: false
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  artportfolio:
    output: true
    permalink: /:collection/:path/
  workportfolio:
    output: true
    permalink: /:collection/:path/
  sideportfolio:
    output: true
    permalink: /:collection/:path/

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
